
on: push

name: Build Releases

jobs:
  build:
    name: linux x86_64
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout JTR
      uses: actions/checkout@v2
      with:
          persist-credentials: false

    - name: Build JTR
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
          apt update && \
          apt dist-upgrade -y && \
          apt install -y python3 python3-pip && \
          pip install -U setuptools && \
          pip install -U pip && \
          pip install -U wheel && \
          ./build_linux.sh && \
          ls -lah dist
