
on: push

name: Build Releases

jobs:

    #build-linux-x86_64:
    #    name: linux x86_64
    #    runs-on: ubuntu-18.04
    #
    #    steps:
    #    - name: Checkout JTR
    #      uses: actions/checkout@v2
    #      with:
    #          persist-credentials: false
    #
    #    - name: Build JTR
    #      env:
    #        IMAGE_TAG: ${{ github.sha }}
    #        TWINE_USERNAME: __token__
    #        TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}
    #      run: |
    #          sudo apt update && \
    #          sudo apt dist-upgrade -y && \
    #          sudo apt install -y python3 python3-pip && \
    #          sudo pip3 install -U setuptools && \
    #          sudo pip3 install -U pip && \
    #          sudo pip3 install -U wheel twine && \
    #          ./build_linux.sh && \
    #          ls -lah dist && \
    #          twine upload --non-interactive --skip-existing dist/*py3-none-manylinux1_x86_64.whl

  ##################
  # Windows x86_64 #
  ##################

  build-windows-x86_64:
    name: Windows x86_64
    runs-on: windows-latest

    steps:
    - name: Checkout JTR
      uses: actions/checkout@v2
      with:
          persist-credentials: false

    - name: Install python
      uses: actions/setup-python@v1
      with:
          python-version: 3.8

    - name: Build JTR
      env:
          IMAGE_TAG: ${{ github.sha }}
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}
      run: |
          choco install -fy cygwin; refreshenv; \
          dir /S C:\tools
          #C:\tools\cygwin\cygwinsetup.exe -q -P libssl-devel -P libbz2-devel
